version: '2'

networks:
  default:
    external:
      name: etalia-network

volumes:
  data:
    external:
      name: etalia-data-volume

services:
  db:
    image: postgres
    hostname: db
    environment:
      - POSTGRES_DB=etalia
      - POSTGRES_USER=etalia
      - POSTGRES_PASSWORD=mypass
    volumes:
      - data:/var/lib/postgresql/data
    container_name: etalia_db

  # Redis
  redis:
    image: redis:2.8.19
    hostname: redis
    container_name: etalia_redis

  # RabbitMQ
  rabbit:
    hostname: rabbit
    image: rabbitmq:3.6.0
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "5672"  # we forward this port because it's useful for debugging
      - "15672"  # here, we can access rabbitmq management plugin
    container_name: etalia_rabbit

  # Django web server
  web:
    image: etalia/python-dev
    command: ./docker/run_web.sh
    env_file: .envs
    volumes:
      - ../.:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbit
      - redis
      - worker
    links:
      - db:db
      - rabbit:rabbit
      - redis:redis
    container_name: etalia_web

  # Celery worker
  worker:
    image: etalia/python-dev
    command: ./docker/run_celery.sh
    env_file: .envs
    volumes:
      - ../.:/code
    depends_on:
      - db
      - rabbit
      - redis
    links:
      - db:db
      - rabbit:rabbit
      - redis:redis
    container_name: etalia_worker
